version: "3"

services:
  mail_check:
    image: registry.yulpa.io/yulpa/check_mails
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # please update OS path following your configuration
      - "C:\\var\\log:/var/log/:rw"
